// Generates platform string resources from spec/strings.json (single source, TR + EN).
//   Android: android/shared/src/main/res/values{,-tr}/strings.xml
//   Apple:   apple/Shared/Resources/Localizable.xcstrings
// {APP_NAME} is replaced with APP_NAME from android/gradle.properties (Android) and
// APP_DISPLAY_NAME from apple/Config/Shared.xcconfig (Apple); fallback "NovaPlayer".
// {0},{1}… are positional STRING args; in plural entries {0} is the INTEGER count.
// Run: node spec/tools/gen-strings.mjs
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
// strings.json + every spec/strings.<area>.json (e.g. strings.android.json, strings.apple.json)
// are merged; a key may be defined only once.
const strings = {};
for (const f of ['strings.json', ...readdirSync(join(root, 'spec')).filter((n) => /^strings\.[a-z0-9-]+\.json$/.test(n)).sort()]) {
  const part = JSON.parse(readFileSync(join(root, 'spec', f), 'utf8')).strings ?? {};
  for (const [k, v] of Object.entries(part)) {
    if (k in strings) throw new Error(`duplicate string key "${k}" in ${f}`);
    if (!v.en || !v.tr) throw new Error(`string "${k}" in ${f} needs both en and tr`);
    strings[k] = v;
  }
}

function readProp(file, key, sep) {
  const f = join(root, file);
  if (!existsSync(f)) return null;
  for (const line of readFileSync(f, 'utf8').split('\n')) {
    const t = line.trim();
    if (t.startsWith('#') || t.startsWith('//')) continue;
    const i = t.indexOf(sep);
    if (i > 0 && t.slice(0, i).trim() === key) return t.slice(i + 1).trim();
  }
  return null;
}
const androidName = readProp('android/gradle.properties', 'APP_NAME', '=') ?? 'NovaPlayer';
const appleName = readProp('apple/Config/Shared.xcconfig', 'APP_DISPLAY_NAME', '=') ?? 'NovaPlayer';

const isPlural = (v) => typeof v === 'object';
const xmlEsc = (s) => {
  let r = s.replace(/\\/g, '\\\\').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/'/g, "\\'").replace(/"/g, '\\"');
  if (r.startsWith('@') || r.startsWith('?')) r = '\\' + r;
  return r;
};
const androidFmt = (s, plural) => s.replace(/\{APP_NAME\}/g, androidName)
  .replace(/\{(\d+)\}/g, (_, n) => (plural && n === '0') ? '%1$d' : `%${+n + 1}$s`);
const appleFmt = (s, plural) => s.replace(/\{APP_NAME\}/g, appleName)
  .replace(/\{(\d+)\}/g, (_, n) => (plural && n === '0') ? '%1$lld' : `%${+n + 1}$@`);

for (const lang of ['en', 'tr']) {
  const lines = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- GENERATED by spec/tools/gen-strings.mjs from spec/strings.json. Do not edit. -->', '<resources>'];
  for (const [key, v] of Object.entries(strings)) {
    if (key === 'app_name') continue; // provided by Gradle resValue (APP_NAME)
    const val = v[lang];
    if (isPlural(val)) {
      lines.push(`    <plurals name="${key}">`);
      for (const q of ['one', 'other']) lines.push(`        <item quantity="${q}">${xmlEsc(androidFmt(val[q], true))}</item>`);
      lines.push('    </plurals>');
    } else {
      const f = androidFmt(val, false);
      const formatted = /%\d+\$/.test(f) ? '' : ' formatted="false"';
      lines.push(`    <string name="${key}"${formatted}>${xmlEsc(f)}</string>`);
    }
  }
  lines.push('</resources>', '');
  const dir = join(root, 'android', 'shared', 'src', 'main', 'res', lang === 'en' ? 'values' : 'values-tr');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'strings.xml'), lines.join('\n'));
}

const xc = { sourceLanguage: 'en', strings: {}, version: '1.0' };
for (const [key, v] of Object.entries(strings)) {
  const loc = {};
  for (const lang of ['en', 'tr']) {
    const val = v[lang];
    if (isPlural(val)) {
      loc[lang] = { variations: { plural: Object.fromEntries(['one', 'other'].map((q) =>
        [q, { stringUnit: { state: 'translated', value: appleFmt(val[q], true) } }])) } };
    } else {
      loc[lang] = { stringUnit: { state: 'translated', value: appleFmt(val, false) } };
    }
  }
  xc.strings[key] = { extractionState: 'manual', localizations: loc };
}
const adir = join(root, 'apple', 'Shared', 'Resources');
mkdirSync(adir, { recursive: true });
writeFileSync(join(adir, 'Localizable.xcstrings'), JSON.stringify(xc, null, 2) + '\n');
console.log(`strings: ${Object.keys(strings).length} keys → Android (${androidName}) + Apple (${appleName})`);
